<?php

/**
 * @file
 * Hooks and callbacks for this module.
 */

/**
 * Implements hook_menu().
 */
function islandora_user_entity_link_menu() {
  $items = array();
  $items['admin/islandora/user_entity_link'] = array(
    'title' => 'User/Entity Link Module',
    'description' => 'Configure Management of relationships between users and entities.',
    'page callback' => 'drupal_get_form',
    'access arguments' => array('administer site configuration'),
    'page arguments' => array('islandora_user_entity_link_admin'),
    'file' => 'includes/admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['islandora_user_entity_link/autocomplete'] = array(
    'page callback' => 'islandora_user_entity_link_autocomplete',
    'access arguments' => array('use autocomplete'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_form_alter().
 */
function islandora_user_entity_link_form_user_profile_form_alter(&$form, $form_state, $form_id) {
  $form['userentity_fieldset'] = array(
    '#type' => 'fieldset',
    '#title' => t('Person Entity'),
    '#weight' => 50,
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );

  $form['userentity_fieldset']['userentity'] = array(
    '#type' => 'textfield',
    '#title' => t('Add link to Entity record'),
    '#size' => 30,
    '#maxlength' => 60,
    '#autocomplete_path' => 'islandora_user_entity_link/autocomplete',
    '#default_value' => '',
    '#weight' => 1,
  );
}

/**
 * Autocomplete callback implementation for the user/object link.
 *
 * @param string $to_complete
 *   The string that needs to be autocompleted.
 */
function islandora_user_entity_link_autocomplete($to_complete) {
  $matches = array();

  $matches['one'] = 'one';
  $matches['two'] = 'two';
  $matches['three'] = 'three';
  $matches['four'] = 'four';
  $matches['five'] = 'five';

  drupal_json_output($matches);
}
